keys:
  - &primary age1ev0c24yd8ddjakymr3uyxv2jzk66lwzmwnpk0vftxnc3xqqdnsmsfge5pv
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *primary
  - path_regex: secrets/gitea-token.yaml$
    key_groups:
      - age:
          - *primary
  - path_regex: secrets/attic.yaml$
    key_groups:
      - age:
          - *primary
  - path_regex: secrets/ssh.yaml$
    key_groups:
      - age:
          - *primary
