{
  config,
  lib,
  pkgs,
  ...
}: let
  themeEnvPath = "$XDG_CONFIG_HOME/theme/env";
  themeEnvFallback = "$HOME/.config/theme/env";
in {
  xdg.configFile = {
    "zsh/.zshrc".text = ''
      # Load system oh-my-zsh setup
      if [ -f /etc/zshrc ]; then
        source /etc/zshrc
      fi

      # Fix for fzf plugin under NixOS
      if command -v fzf >/dev/null; then
        export FZF_BASE=$(dirname $(dirname $(which fzf)))
      fi

      # Load theme colors generated by hm.theme
      if [ -f ${themeEnvPath} ]; then
        source ${themeEnvPath}
      elif [ -f ${themeEnvFallback} ]; then
        source ${themeEnvFallback}
      fi

      export COLORTERM=truecolor
      setopt PROMPT_SUBST

      # Safe fallbacks if THEME_* aren’t present
      : ''${THEME_ACCENT1:='#d65d0e'}
      : ''${THEME_PRIMARY:='#458588'}
      : ''${THEME_MUTED:='#bdae93'}
      : ''${THEME_FG:='#ebdbb2'}
      : ''${THEME_SUCCESS:='#98971a'}
      : ''${THEME_WARNING:='#d79921'}
      : ''${THEME_ERROR:='#cc241d'}

      __theme_git_branch() {
        command git rev-parse --is-inside-work-tree >/dev/null 2>&1 || return
        command git branch --show-current 2>/dev/null
      }

      PROMPT='%F{'$THEME_ACCENT1'}%n%f@%F{'$THEME_PRIMARY'}%m%f %F{'$THEME_MUTED'}%~%f %# '
      RPROMPT='%F{'$THEME_SUCCESS'}$(__theme_git_branch)%f'
    '';

    "zsh/README-theme.txt".text = ''
      This zsh reads theme colors from ~/.config/theme/env (generated by hm.theme).
      Colors: THEME_BG/FG/MUTED/BORDER/PRIMARY/SECONDARY/SUCCESS/WARNING/ERROR/HINT/ACCENT1/2/3
      Prompt uses zsh truecolor via %F{#rrggbb}.
    '';
  };
}
