name: CI — build & lint flake

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Show Nix version
        run: nix --version

      - name: Check formatting (treefmt)
        run: nix develop -c treefmt --ci

      - name: Statix lints
        run: nix run nixpkgs#statix -- check .

      - name: Deadnix (dead code)
        run: nix run nixpkgs#deadnix -- .

      - name: Flake checks
        run: nix flake check --all-systems

      - name: Build all NixOS hosts
        shell: bash
        run: |
          set -euo pipefail
          hosts=$(nix eval --json .#nixosConfigurations --apply 'builtins.attrNames' | jq -r '.[]' || true)
          if [[ -n "${hosts}" ]]; then
            for h in ${hosts}; do
              echo "Building host: ${h}"
              nix build ".#nixosConfigurations.${h}.config.system.build.toplevel"
            done
          else
            echo "No nixosConfigurations found; skipping host builds."
          fi
