git:
  userName: ENC[AES256_GCM,data:yrXDUKST1IL3,iv:04NRT6Jcni6ZPHOMic8ifTuxUBaAxVqJoX6ftVBYxqk=,tag:GYOMk2IMfKANj6IdkMx+gA==,type:str]
  userEmail: ENC[AES256_GCM,data:daC1I7ZmeljzDySipPvMT5JdW8w6dOv6abfMzeS17+iF5Hd+IGYsTJQboA==,iv:fy9nXPD5Sag0ciCKm9t7ZrBTLKyGnqoxsPDLDSl7qLM=,tag:0dktXpcm4I+/vil/u2JDrQ==,type:str]
work:
  internal_domain: ENC[AES256_GCM,data:ogLn2NyyD/I=,iv:eHXEavEVnPHzmXEuwHRcFUOj8q7E21kqsHs44tDdBk4=,tag:nwed9kKa8wgh80ypiUag4g==,type:str]
wireguard:
  mia:
    keys:
      private: ENC[AES256_GCM,data:R7jTg/ik+3/mbpl/ol5+fMdM4g4GlYwoDWXfpKhmFmdDFsObtlqRDGXWW3k=,iv:4Fs8RVSLFqwp5ermDqax34gZ0hDCVb1kYYFgcXNBgY8=,tag:KGST8aijh6DVzCmPMkkTYw==,type:str]
      public: ENC[AES256_GCM,data:B//Gh3sYzaTMaRdrmEu41kV5KPgP5xSAuRTitORRYVNwmFv39qt8NFKg2NA=,iv:OFGOBgrRfFhT07FZxAH94tkbVOVDrc0WO5t5Na0P2NQ=,tag:9WB+mBia6zXjldtsDd2VAw==,type:str]
  vps:
    keys:
      public: ENC[AES256_GCM,data:3nIabg2de9URwT/jQCyMckuao+aB3OhZ48CKk8W2oiudsq0QHEEVxF/n9Ak=,iv:UgWjD8LAX2RO5oIyC+3PfBKq+DfddTCfOzqRpGW04to=,tag:ctoxjtr2crcbo7SJs/YwfA==,type:str]
bsw:
  servers:
    gitea:
      domain: ENC[AES256_GCM,data:MlB/krW8gBROwNnsGMMFJw==,iv:ZlLh5h89MEZ1fbRGVHfFQ9qYnzod4VqbRwBGOpt4bCo=,tag:B46IzhylEeqrueaHSxbbeg==,type:str]
      ip: ENC[AES256_GCM,data:nr8Ye/20fLwND9Y=,iv:5JYBi4P8n5HQBQ7NLPp+ZjSsRc4rqTsHOUBrkOoEPLI=,tag:ecm2vrRpXnGsDL66FzALcg==,type:str]
      token: ENC[AES256_GCM,data:Hi/J/qzZQB2Cpoj1XqlVaNM0i0RSNZa0MyYavkNXC7RfCi6fE8A0vA==,iv:YBqSAo61PcLaUYwNr7f0r/fWs/2liwBFbQ12Rx5w3m4=,tag:QuXgX7Say7TUDNj20UNJ3g==,type:str]
esphome:
  wifi_ssid: ENC[AES256_GCM,data:mfdm,iv:sSwf0y8chAqD42puRsydGMmRAuBUxnshVfh04uogiV8=,tag:ZTtU2/hsdGREmA4YWwtKtg==,type:str]
  wifi_password: ENC[AES256_GCM,data:/ZMbYL2Qn7T/1aU=,iv:KVMbym5D5MOirMS59Ah6/GbHDXVUqoaTq/KqVyqtuEo=,tag:OK0Tw6as/jxXSKj5wSU9cQ==,type:str]
  ota_password: ENC[AES256_GCM,data:8mOVchcZ3gFJu8E=,iv:MHjokWAQ4A34rypSQH70hTJsKcmEQ5H0gSCGqeAfwzY=,tag:a45f3CHmliUwm+ecDBtaIw==,type:str]
  mqtt_broker: ENC[AES256_GCM,data:2cOwADQAUXaS8q8=,iv:BTQrh5bbFfai3pYdNeW5nrSY3jNW2dtUefJnokZi8J8=,tag:W3xLq1zM643pCcV7UTuj2w==,type:str]
  mqtt_port: ENC[AES256_GCM,data:ihSjow==,iv:WSMlyt7fdZ+y+60YI8ApZ6KI1YC267ZJX8s9C/0m6AI=,tag:aLISHpz2kGoxD5iqCznaDg==,type:int]
  mqtt_user: ENC[AES256_GCM,data:H0f5aRM3y7Se,iv:as1Xun42AQ0V9QyZC84QGawAGQqS4HycXUsu0FnFXqQ=,tag:FGprDO/8Wxes3hMcExOw1A==,type:str]
  mqtt_password: ENC[AES256_GCM,data:DWkLHoRjkke0,iv:kquwy9M6FgSS89EcUkrXbqGJ6xfN9ZnfS7SOeass25E=,tag:DnrxPoQ8CyQK064oDVvzvQ==,type:str]
network-manager.env: ENC[AES256_GCM,data:gbpp24P7NXxM/T8zd8Yf8vgiKHnEb/lKTdJnhUQOZCvCw2yKlUDE5QNzkbOhPT+P8mPXUntyZhKQgtM7Pf1VT/DXgFRC+864KSLqg6rbItdQv5IQI8/+bHycTPq/om5TKetrQgeaAsT1fFlqjIhkEmZwO7YI4TXIBxhm3GBUYcP2/Ifskhb2eNZWoLdIMTZcFKmL6ZSLJRt1H3KjzUS8zLVJR+NP1hQPqRSu5iru0+W3cO9eWCX0afGD09bkR5wP6+Paoe+8P5FnuGuu0sb7uJTCBsern/jxeyO5Ea34UaLXkEWDhlBIFXdLqrL8Rglzm5FHlL1XzmOsmlUTW/EcP+G0GwprzxEeTvSJiweFttGGAQQoduvTBi9Tz8e4JnQOpDNxPpWaesaHjxauJ36mIsAEVjNKlk3f41wSvhN/m0VAvFfcxkk5O8tok8X3OJGGaS/YmEYof8aDYwIcVGd+JcDfhkNhl2N85QNSHd6pvLyQowLP6BGqfSCGRWmg1g5Xy0oycpZEpXhUK0RbfA38nKWXzO6tWsSE1Pd+CO3sYVSkYyR/3lqEsM5dMMhRuEn0+i8BdmBp6RTwLYDOv/zNdaGYIIDOgnkqjUkTO4/xYzSh/5G97fIcU9IMQ3hk9In195WFWkRUrqxwNauXLI7WvuEDT8GqldRcBjYnMohOSzzZ6eHVLasmuFdHnQbS06Ooru3ZlCWPyo02LuF+Qli178p4clqZXyqLwcvZH+9sx9+jl71TMKqddOER0AlSMZEWwdPKHuq6zod4THSM1U535GbCmr9lou8tuKyATJ7LconnNB6732x8yzooLnskbHi5cqV12fMNHHw3lbR7+CFQLy7g+QbzhhxxhxCFRIk2XXtRC8Fl193mWajpbt1Ztzx/OoVoCxKSR/RcqufIadYW5/1K+0dG5efJZ5mIbzQsgTY9bQMVjGdwZEJnNcl1Fk/5mtMYciDaw652WxYYQjFeUPbzRKWDjrfxYfKJ5v1EZ83d+C3Ej85WH/s32Nmoa78AuPUSbeX0rD8U1n36PxieCOMC7HCdKQchMlMpXbWZbDl+STxUievgta3R+t+FClKHYmFjlFSbY6jsjyhZG11606aaP0Mt18Te+XQgZfZ9q2Y1q1gazVUlfKZA1UCvH1Gw0AmCzvHm/gPnQJgEKaqNp8tjm5fwIu4uTz09W8e6/vHuxdEm9S8MyJ7xlTHepNv7538h9yEMenTyqoJdffOlmbq5bUnPHOo/nD+ArjKNukWb1ZtRnWoUzROLOpFw2HRqFnBHqLUuEClqSu4vV3lSKfMrcLokwggU2sABQcH+GgK+EuTZQjAB02Yjjh6Fwu41+TuuvjvkkXRVLbwI196bsG95lP93GMymCCgx9P2qh52DaaPDw9O3M3SNJciY9atkWBuX0HT1W7qauoYlYTRSs56NtDfAqH5iLhWFGXx4yc2Hlq4HrbivD/iGTK+sFIWhTfBcy+nrJ8VOjpFVHm+2Ge2xO9n51RkrjNVWqzrJ+qHeg3AMlYNVwPkUiZytc0XW6S3NLry9J/foFqnBfZx1hhu0yXJQ/Lrq0/d/OPEI4gIkSS1XE+hVlJLy19RbH1F7gzHEqWPSWpA2RHSKlwbC3J/bPTEvLNaf/D3wN4dsq9uqs2ww9B3MevaHac/sHVUM7APjkdPyFX+ROKOZw1KGTioPeNjPTRYiPdc9ujsIaz0=,iv:ZAUfV2LgTS71SOBddl7PczO4N6a3RFmwBOFREuC7Thw=,tag:jXdZRw6GG+1jsAPxI7imzw==,type:str]
sops:
  age:
    - recipient: age1ev0c24yd8ddjakymr3uyxv2jzk66lwzmwnpk0vftxnc3xqqdnsmsfge5pv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaS9oamI1SWtQbkdGQldm
        c280eGpVTjJHZkkvejJCNEtFdlpqK1BuWmtVCm5HVzhhYm5jZ3VwaGljektlSDBm
        U1FLSzYvRFZMOWtDS201OFIxVU03MXMKLS0tIDQ0NkFqNXd2MFp0V3RETmpkUGNj
        N3U3bmRqL2JNaTN3ZXQrRUZuUnE4ODQKHGZdDJ8GSTCAhcTKdz0K0awYGDSmY4ae
        905xorZzrTq6yTq654y7/fgKQmHdo8F7sUAua15XP+1WiFt0uDH6pA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-09T09:36:44Z"
  mac: ENC[AES256_GCM,data:F6K+/vwxagke3JLpz4dXkcr8qglaDxZbKbaMmTvXzLwOWvze1kcn6qzspETM9PRe7VsO1QpjbvhaGFww70VTYM2DHSAW6/o9D2xbkUpHLIy6hy9Qgw3/xU5ugOqIMTSQqq9WGd1X9y74zCXKvZ4632P1k4AFZ36IXm/w9gq6VV0=,iv:nZ+3gIpQRmeWckg4UMOIKCfQSRdm1cSrezq9eZCOlnc=,tag:0y6CulYs9dc8Mktwb4n7Dw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
