hello: ENC[AES256_GCM,data:DAkBwcW7toRA2kNSjGwIxKZiGTIib3zPp/YeclgPwdqbEfQlZ5+5rtO6YcCzeg==,iv:LhUkJCYUDTvwPUHxpcrSSOC6mz6SK3mthFPAv5Dh3NU=,tag:Ef6dI7IQz9/keAyPMJrPdQ==,type:str]
wireguard:
    mia:
        keys:
            private: ENC[AES256_GCM,data:R7jTg/ik+3/mbpl/ol5+fMdM4g4GlYwoDWXfpKhmFmdDFsObtlqRDGXWW3k=,iv:4Fs8RVSLFqwp5ermDqax34gZ0hDCVb1kYYFgcXNBgY8=,tag:KGST8aijh6DVzCmPMkkTYw==,type:str]
            public: ENC[AES256_GCM,data:B//Gh3sYzaTMaRdrmEu41kV5KPgP5xSAuRTitORRYVNwmFv39qt8NFKg2NA=,iv:OFGOBgrRfFhT07FZxAH94tkbVOVDrc0WO5t5Na0P2NQ=,tag:9WB+mBia6zXjldtsDd2VAw==,type:str]
    vps:
        keys:
            public: ENC[AES256_GCM,data:3nIabg2de9URwT/jQCyMckuao+aB3OhZ48CKk8W2oiudsq0QHEEVxF/n9Ak=,iv:UgWjD8LAX2RO5oIyC+3PfBKq+DfddTCfOzqRpGW04to=,tag:ctoxjtr2crcbo7SJs/YwfA==,type:str]
esphome:
    wifi_ssid: ENC[AES256_GCM,data:mfdm,iv:sSwf0y8chAqD42puRsydGMmRAuBUxnshVfh04uogiV8=,tag:ZTtU2/hsdGREmA4YWwtKtg==,type:str]
    wifi_password: ENC[AES256_GCM,data:/ZMbYL2Qn7T/1aU=,iv:KVMbym5D5MOirMS59Ah6/GbHDXVUqoaTq/KqVyqtuEo=,tag:OK0Tw6as/jxXSKj5wSU9cQ==,type:str]
    ota_password: ENC[AES256_GCM,data:8mOVchcZ3gFJu8E=,iv:MHjokWAQ4A34rypSQH70hTJsKcmEQ5H0gSCGqeAfwzY=,tag:a45f3CHmliUwm+ecDBtaIw==,type:str]
    mqtt_broker: ENC[AES256_GCM,data:2cOwADQAUXaS8q8=,iv:BTQrh5bbFfai3pYdNeW5nrSY3jNW2dtUefJnokZi8J8=,tag:W3xLq1zM643pCcV7UTuj2w==,type:str]
    mqtt_port: ENC[AES256_GCM,data:ihSjow==,iv:WSMlyt7fdZ+y+60YI8ApZ6KI1YC267ZJX8s9C/0m6AI=,tag:aLISHpz2kGoxD5iqCznaDg==,type:int]
    mqtt_user: ENC[AES256_GCM,data:H0f5aRM3y7Se,iv:as1Xun42AQ0V9QyZC84QGawAGQqS4HycXUsu0FnFXqQ=,tag:FGprDO/8Wxes3hMcExOw1A==,type:str]
    mqtt_password: ENC[AES256_GCM,data:DWkLHoRjkke0,iv:kquwy9M6FgSS89EcUkrXbqGJ6xfN9ZnfS7SOeass25E=,tag:DnrxPoQ8CyQK064oDVvzvQ==,type:str]
network-manager.env: ENC[AES256_GCM,data:a5JT4hzPLHw8yctBFdVQcIjo1+uSrMyuEJLSDGdu4SBU/GSkVYzJkacLBMOCabFfwYTsohXqeFaDQoSvQWf+TO3rub8xV40bUkzf37imio3MaYvEj3N4p+gz+6XOZLVdwsn6yN4Gqq5bAbfeNvlt9Wi9gwC9qlkXf+bdeIyGfA5efLAX+T/KlLgrx+VKtyfXr5PNrr/Pw/PoIltJIX8VaPiVZlFnG2k+1xm4rOm0xQqChA+wL5+vXj158dMD8ywgt758AjBLIi+nR3l6AwQjmb6xiM0WYhSR2YjQsPedKImQbBDiO98C70Kr1Db4BWPqvlWg1T7LXMmB6akUs2b+M1pqenjoMKYsHGNLjvJfj8mcJNP2tpk4c4HjSuHY6R07PBnMUxBEfdFadnDzeDIJTE3CJWq+oQjOMf8HUZvI+yyRG/5AA7BHlrtHg0pm8gyV/9gJOENqET7OU1oDXo1kVDCnaxxJ29dWXlPgxOtCGw/ogUjxHW0Ay0pDzsMuhq9klDMHrJhJOCzHt4X2nflPngky4EkyPYOpudcE9qbpqCGul7WLV4dfaG0etLnB4FA0QMbamkwji5LUStlfjM7ZZdGqr0mJjjlIk1ALvcmsk53J8RKekpypb39ow1U4d+sCZSmQI7aYIkUZt1XA1LvznUd8mnIo/m67G52HpBjNYr4dGxnf2NV1FIajI1trR5SfYvHi/305qpfpoj9FC0u5fWJtLTlZcgmxTRwVBuqfhLDyv+gjzi65gWRN3x/S8C+dRH6W7rLFwDIeIr20RhQYdHrz8xFPdLk6putQ01IYhx+RgZy/H2laO5OgPo+fFER8RU2c4k/PYZ6cEwGMYxjjUAmdY4552COFT/HSCIC6LmyYNykWg4dKXe0G/MwAy6ECUCpkbh40b3cn4CfecaF1zMYDLqk7Vy2d+Gx84A/J4BOaRD/2Xcbb/6CHFZMMOyLmCUr7CBi2d8jIjAptx8hHBEODY5k5/OyfNJeSfWxweuB5Xce2IQBp2FWi9TXbt0rqooLtjfgaYk64IW+uoboPomTpI3lib/Zq8G9kxBPx4KxxVovwdw6jokd5tNhqsQCVd2SfaenwMibFjP3QV+LxQ4ptBLoc47w38MghmSEv6g/o74VkzjLC0QnXk34fEPDQKTSTKmc7DLMim6CGt4Ij+H2S3D+JcwjP4JUzsNDGZjA+BiPFe5OsK3wSrP3GL1WJPhSsGI0QVPQ95Er3R5Hd0LWxbG0OHMewCgYCQTcpjrTFaLYNE4IXJO5NIadGQE6G8mjOv6xnHj6GuxjrxChImHxOvXlAd2DjxHMM+pd5w3eh0iZ+2Had8EmIJBgbxIvMMiMWbQ97Uv2Bnt0Z2cDM9SuRAWlLGg==,iv:KEUVTGSchlfngGLciE/16AOWwmfKlxs3sr4Iz2Bc0o4=,tag:bihpTpJuhrxoTAJHZhprsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ev0c24yd8ddjakymr3uyxv2jzk66lwzmwnpk0vftxnc3xqqdnsmsfge5pv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaS9oamI1SWtQbkdGQldm
            c280eGpVTjJHZkkvejJCNEtFdlpqK1BuWmtVCm5HVzhhYm5jZ3VwaGljektlSDBm
            U1FLSzYvRFZMOWtDS201OFIxVU03MXMKLS0tIDQ0NkFqNXd2MFp0V3RETmpkUGNj
            N3U3bmRqL2JNaTN3ZXQrRUZuUnE4ODQKHGZdDJ8GSTCAhcTKdz0K0awYGDSmY4ae
            905xorZzrTq6yTq654y7/fgKQmHdo8F7sUAua15XP+1WiFt0uDH6pA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-16T08:20:16Z"
    mac: ENC[AES256_GCM,data:NRCkK97LB9eoB6IwrdyxLU4W8WOmEIsruLBY4wdw5hJa0YWKOms9nX+hhewMCJ44/bfPSkyEdQVqHKeoZtRbBDrzBIqjqh0PKgiKcdrejPr1Dkc0gjSDQVsa0oKUyXZBDMGqp7WPPVsQLNuOb3RTO4aPMwJVHIDmkY6l5AC16mU=,iv:2I+sVNQss7UFpm1YW+zun8nRuE6isPPqldy9XKlX1M8=,tag:jrbg4HPZjCwDe9I/QnY1pA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
